cabal-version: 3.8
name: penance-planner
version: 0.1.0.0
build-type: Simple
license: MIT

executable penance-planner
  main-is: Main.hs
  hs-source-dirs: src
  other-modules:
    Penance.Json
    Penance.Plan
    Penance.Graph.Component
    Penance.Graph.Module
    Penance.Graph.Package
    Penance.Graph.TH
    Penance.Graph.Backpack
    Penance.Emit.Drv
  build-depends:
    base >=4.18 && <5,
    containers,
    directory,
    filepath
  default-language: Haskell2010
  ghc-options: -Wall

executable penance-architecture-bench
  main-is: ArchitectureBenchMain.hs
  hs-source-dirs: src
  other-modules:
    Penance.Json
  build-depends:
    base >=4.18 && <5,
    directory,
    filepath,
    process,
    time
  default-language: Haskell2010
  ghc-options: -Wall

executable penance-bench
  main-is: BenchMain.hs
  hs-source-dirs: src
  build-depends:
    base >=4.18 && <5,
    directory,
    filepath,
    process,
    time
  default-language: Haskell2010
  ghc-options: -Wall

executable penance-plan
  main-is: PlanMain.hs
  hs-source-dirs: src
  other-modules:
    Penance.Dyndrv
    Penance.GhcMakefile
    Penance.Json
    Penance.ModulePlan
  build-depends:
    base >=4.18 && <5,
    containers,
    directory,
    filepath,
    process
  default-language: Haskell2010
  ghc-options: -Wall

executable penance-rebuild-bench
  main-is: RebuildBenchMain.hs
  hs-source-dirs: src
  other-modules:
    Penance.Json
  build-depends:
    base >=4.18 && <5,
    directory,
    filepath,
    process,
    time
  default-language: Haskell2010
  ghc-options: -Wall

executable penance-lock
  main-is: LockMain.hs
  hs-source-dirs: src
  other-modules:
    Penance.Json
  build-depends:
    base >=4.18 && <5,
    Cabal,
    bytestring,
    directory,
    filepath
  default-language: Haskell2010
  ghc-options: -Wall

executable normalize-project
  main-is: WasmPlannerMain.hs
  hs-source-dirs: src
  other-modules:
    Penance.Blake3
    Penance.Json
    Penance.Utf8
    Penance.WasmPlanner
  build-depends:
    base >=4.18 && <5
  default-language: Haskell2010
  ghc-options: -Wall

test-suite wasm-planner-tests
  type: exitcode-stdio-1.0
  main-is: WasmPlannerTestMain.hs
  hs-source-dirs: src
  other-modules:
    Penance.Blake3
    Penance.Json
    Penance.Utf8
    Penance.WasmPlanner
  build-depends:
    base >=4.18 && <5
  default-language: Haskell2010
  ghc-options: -Wall
