cabal-version: 3.8
name: backpack-multi-instance
version: 0.1.0.0
build-type: Simple
license: MIT

library
  exposed-modules: UsesSignature
  signatures: Data.MyAbstractMap
  hs-source-dirs: src
  build-depends: base >=4.20 && <5
  default-language: Haskell2010

library list-map
  exposed-modules: Impl.ListMap
  hs-source-dirs: impl-list
  build-depends: base >=4.20 && <5
  default-language: Haskell2010

library tagged-map
  exposed-modules: Impl.TaggedMap
  hs-source-dirs: impl-tagged
  build-depends: base >=4.20 && <5
  default-language: Haskell2010

executable list-user
  main-is: ListUser.hs
  hs-source-dirs: app
  build-depends:
    base >=4.20 && <5,
    backpack-multi-instance,
    backpack-multi-instance:list-map
  mixins:
    backpack-multi-instance:list-map (Impl.ListMap as Data.MyAbstractMap)
  default-language: Haskell2010

executable tagged-user
  main-is: TaggedUser.hs
  hs-source-dirs: app
  build-depends:
    base >=4.20 && <5,
    backpack-multi-instance,
    backpack-multi-instance:tagged-map
  mixins:
    backpack-multi-instance:tagged-map (Impl.TaggedMap as Data.MyAbstractMap)
  default-language: Haskell2010
