cabal-version: 3.0
name: module-cutoff-thirty
version: 0.1.0.0
build-type: Simple

library
  exposed-modules:
    Cutoff.M01,
    Cutoff.M02,
    Cutoff.M03,
    Cutoff.M04,
    Cutoff.M05,
    Cutoff.M06,
    Cutoff.M07,
    Cutoff.M08,
    Cutoff.M09,
    Cutoff.M10,
    Cutoff.M11,
    Cutoff.M12,
    Cutoff.M13,
    Cutoff.M14,
    Cutoff.M15,
    Cutoff.M16,
    Cutoff.M17,
    Cutoff.M18,
    Cutoff.M19,
    Cutoff.M20,
    Cutoff.M21,
    Cutoff.M22,
    Cutoff.M23,
    Cutoff.M24,
    Cutoff.M25,
    Cutoff.M26,
    Cutoff.M27,
    Cutoff.M28,
    Cutoff.M29,
    Cutoff.M30
  hs-source-dirs: src
  build-depends: base >=4.20 && <5
  default-language: Haskell2010

executable module-cutoff-30
  main-is: Main.hs
  hs-source-dirs: app
  build-depends:
    base >=4.20 && <5,
    module-cutoff-thirty
  default-language: Haskell2010
