module Main (main) where

import Control.Monad (forM, unless, when)
import qualified Data.ByteString as BS
import Data.Char (isSpace)
import Data.List (dropWhileEnd, isPrefixOf, nub, sort, sortOn, stripPrefix)
import Data.Maybe (fromMaybe)
import Distribution.Fields.ParseResult (runParseResult)
import Distribution.PackageDescription
  ( Benchmark (..)
  , BenchmarkInterface (..)
  , BuildInfo (..)
  , Executable (..)
  , Library (..)
  , PackageDescription (..)
  , TestSuite (..)
  , TestSuiteInterface (..)
  , buildType
  , pkgName
  , pkgVersion
  )
import Distribution.PackageDescription.Configuration (flattenPackageDescription)
import Distribution.PackageDescription.Parsec (parseGenericPackageDescription)
import Distribution.Pretty (prettyShow)
import Distribution.Types.Dependency (Dependency)
import Distribution.Types.LibraryName (LibraryName (..))
import Penance.Json (Json)
import qualified Penance.Json as Json
import System.Directory (listDirectory)
import System.Environment (getArgs)
import System.Exit (die, exitFailure, exitSuccess)
import System.FilePath ((</>), takeExtension, takeFileName)

data Options = Options
  { optProject :: FilePath
  , optCompiler :: String
  , optIndexState :: String
  , optOut :: Maybe FilePath
  , optCheck :: Maybe FilePath
  }
  deriving (Eq, Show)

data PackageLock = PackageLock
  { lockPackagePath :: FilePath
  , lockCabalFile :: FilePath
  , lockDescription :: PackageDescription
  }

data ExternalUnit = ExternalUnit
  { externalUnitName :: String
  , externalUnitVersion :: String
  , externalUnitSource :: ExternalSource
  }

data ExternalSource
  = GhcBoot
  | HackageSdist
      { hackageSdistUrl :: String
      , hackageSdistSha256 :: String
      }

main :: IO ()
main = do
  opts <- parseOptions =<< getArgs
  packages <- readProjectPackages opts
  externalUnits <- resolveExternalUnits opts packages
  let rendered = Json.renderJson (lockJson opts packages externalUnits) ++ "\n"
  case optCheck opts of
    Just path -> do
      expected <- readFile path
      unless (expected == rendered) $ do
        putStrLn ("penance-lock: lock is stale: " ++ path)
        putStrLn "expected checked-in lock to match generated lock"
        exitFailure
    Nothing ->
      pure ()
  case optOut opts of
    Just path -> writeFile path rendered
    Nothing ->
      when (optCheck opts == Nothing) (putStr rendered)
  exitSuccess

parseOptions :: [String] -> IO Options
parseOptions =
  go
    Options
      { optProject = "."
      , optCompiler = "ghc-9.10.2"
      , optIndexState = "2026-02-01T00:00:00Z"
      , optOut = Nothing
      , optCheck = Nothing
      }
  where
    go opts args =
      case args of
        [] -> pure opts
        "--project" : value : rest -> go opts {optProject = value} rest
        "--compiler" : value : rest -> go opts {optCompiler = value} rest
        "--index-state" : value : rest -> go opts {optIndexState = value} rest
        "--out" : value : rest -> go opts {optOut = Just value} rest
        "--check" : value : rest -> go opts {optCheck = Just value} rest
        "-h" : _ -> usage >> exitSuccess
        "--help" : _ -> usage >> exitSuccess
        flag : _ -> die ("unknown option: " ++ flag)

usage :: IO ()
usage =
  putStrLn $
    unlines
      [ "usage: penance-lock [--project DIR] [--compiler GHC] [--index-state TS] [--out FILE] [--check FILE]"
      , ""
      , "Generate a deterministic unit lock from cabal.project using Cabal as a library."
      , "--check compares the generated bytes with an existing lock file."
      ]

readProjectPackages :: Options -> IO [PackageLock]
readProjectPackages opts = do
  projectText <- readFile (optProject opts </> "cabal.project")
  let packagePaths = simpleProjectPackages projectText
  locks <- forM packagePaths $ \packagePath -> do
    cabalFile <- findCabalFile (optProject opts) packagePath
    cabalBytes <- BS.readFile cabalFile
    generic <-
      case runParseResult (parseGenericPackageDescription cabalBytes) of
        (_warnings, Right value) -> pure value
        (_warnings, Left err) -> die ("penance-lock: failed to parse " ++ cabalFile ++ ": " ++ show err)
    pure
      PackageLock
        { lockPackagePath = packagePath
        , lockCabalFile = makeRelativeProject packagePath cabalFile
        , lockDescription = flattenPackageDescription generic
        }
  pure (sortOnPackage locks)

findCabalFile :: FilePath -> FilePath -> IO FilePath
findCabalFile projectRoot packagePath = do
  let dir = if packagePath == "." then projectRoot else projectRoot </> packagePath
  entries <- listDirectory dir
  let cabalFiles = sort [entry | entry <- entries, takeExtension entry == ".cabal"]
  case cabalFiles of
    [name] -> pure (dir </> name)
    [] -> die ("penance-lock: no .cabal file found in " ++ dir)
    _ -> die ("penance-lock: multiple .cabal files found in " ++ dir)

makeRelativeProject :: FilePath -> FilePath -> FilePath
makeRelativeProject packagePath cabalFile =
  if packagePath == "."
    then takeFileName cabalFile
    else packagePath </> takeFileName cabalFile

simpleProjectPackages :: String -> [FilePath]
simpleProjectPackages text =
  case collectProjectFieldPackages "packages" (projectLineRecords text) of
    [] -> ["."]
    paths -> sort (nub paths)

projectLineRecords :: String -> [(String, Bool)]
projectLineRecords text =
  [ (trim (stripComment line), isIndented (stripComment line))
  | line <- lines text
  , trim (stripComment line) /= ""
  ]

collectProjectFieldPackages :: String -> [(String, Bool)] -> [FilePath]
collectProjectFieldPackages field records =
  case records of
    [] -> []
    (line, indented) : rest
      | not indented && (field ++ ":") `isPrefixOf` line ->
          let inline = trim (drop (length field + 1) line)
              (continuation, remaining) = span snd rest
              value = unlines (inline : map fst continuation)
           in splitProjectPackageWords value ++ collectProjectFieldPackages field remaining
      | otherwise -> collectProjectFieldPackages field rest

splitProjectPackageWords :: String -> [FilePath]
splitProjectPackageWords value =
  filter (/= "") $
    map (trim . removeSuffix ",") $
      words (map (\ch -> if ch == '\t' || ch == '\n' then ' ' else ch) value)

lockJson :: Options -> [PackageLock] -> [ExternalUnit] -> Json
lockJson opts packages externalUnits =
  Json.object
    [ ("schema", Json.string "penance/strata-lock/1")
    , ("compiler", Json.string (optCompiler opts))
    , ("indexState", Json.string (optIndexState opts))
    , ( "project"
      , Json.object
          [ ("root", Json.string ".")
          , ("pathBase", Json.string "project-root")
          , ("cabalProject", Json.string "cabal.project")
          , ("packages", Json.array (map (Json.string . lockPackagePath) packages))
          ]
      )
    , ("packages", Json.array (map packageJson packages))
    , ("externalUnits", Json.array (map externalUnitJson externalUnits))
    ]

packageJson :: PackageLock -> Json
packageJson packageLock =
  let desc = lockDescription packageLock
   in Json.object
        [ ("name", Json.string (prettyShow (pkgName (package desc))))
        , ("version", Json.string (prettyShow (pkgVersion (package desc))))
        , ("path", Json.string (lockPackagePath packageLock))
        , ("cabalFile", Json.string (lockCabalFile packageLock))
        , ("setupType", Json.string (prettyShow (buildType desc)))
        , ("components", Json.array (componentsJson desc))
        ]

componentsJson :: PackageDescription -> [Json]
componentsJson desc =
  sortOn renderedName $
    maybe [] (\lib -> [libraryJson "lib" lib]) (library desc)
      ++ map subLibraryJson (subLibraries desc)
      ++ map executableJson (executables desc)
      ++ map testSuiteJson (testSuites desc)
      ++ map benchmarkJson (benchmarks desc)
  where
    renderedName value =
      case value of
        Json.JsonObject fields ->
          case lookup "name" fields of
            Just (Json.JsonString name) -> name
            _ -> ""
        _ -> ""

libraryJson :: String -> Library -> Json
libraryJson name lib =
  componentJson name "library" (libBuildInfo lib) (map prettyShow (exposedModules lib)) (map prettyShow (signatures lib)) Nothing

subLibraryJson :: Library -> Json
subLibraryJson lib =
  libraryJson (libraryComponentName (libName lib)) lib

executableJson :: Executable -> Json
executableJson exe =
  componentJson ("exe:" ++ prettyShow (exeName exe)) "executable" (buildInfo exe) [modulePath exe] [] (Just (modulePath exe))

testSuiteJson :: TestSuite -> Json
testSuiteJson test =
  componentJson ("test:" ++ prettyShow (testName test)) "test-suite" (testBuildInfo test) (maybe [] (: []) (testSuiteMainPath test)) [] (testSuiteMainPath test)

benchmarkJson :: Benchmark -> Json
benchmarkJson bench =
  componentJson ("bench:" ++ prettyShow (benchmarkName bench)) "benchmark" (benchmarkBuildInfo bench) (maybe [] (: []) (benchmarkMainPath bench)) [] (benchmarkMainPath bench)

libraryComponentName :: LibraryName -> String
libraryComponentName libraryName =
  case libraryName of
    LMainLibName -> "lib"
    LSubLibName name -> "lib:" ++ prettyShow name

componentJson :: String -> String -> BuildInfo -> [String] -> [String] -> Maybe FilePath -> Json
componentJson name kind buildInfo' modules signatures' mainPath =
  Json.object
    [ ("name", Json.string name)
    , ("kind", Json.string kind)
    , ("sourceDirs", stringArray (sort (map prettyShow (hsSourceDirs buildInfo'))))
    , ("modules", stringArray (sort modules))
    , ("main", maybe Json.JsonNull Json.string mainPath)
    , ("signatures", stringArray (sort signatures'))
    , ("dependencies", stringArray (sort (map prettyShow (targetBuildDepends buildInfo'))))
    , ("defaultExtensions", stringArray (sort (map prettyShow (defaultExtensions buildInfo'))))
    ]

testSuiteMainPath :: TestSuite -> Maybe FilePath
testSuiteMainPath test =
  case testInterface test of
    TestSuiteExeV10 _ path -> Just path
    TestSuiteLibV09 _ moduleName -> Just (moduleNameToPath (prettyShow moduleName))
    TestSuiteUnsupported _ -> Nothing

benchmarkMainPath :: Benchmark -> Maybe FilePath
benchmarkMainPath bench =
  case benchmarkInterface bench of
    BenchmarkExeV10 _ path -> Just path
    BenchmarkUnsupported _ -> Nothing

moduleNameToPath :: String -> FilePath
moduleNameToPath =
  map (\ch -> if ch == '.' then '/' else ch) . (++ ".hs")

resolveExternalUnits :: Options -> [PackageLock] -> IO [ExternalUnit]
resolveExternalUnits opts packages = do
  let localNames =
        sort (map (prettyShow . pkgName . package . lockDescription) packages)
      directExternalNames =
        sort . nub . filter (`notElem` localNames) $
          concatMap (componentDependencyNames . lockDescription) packages
      externalNames =
        expandExternalClosure directExternalNames
  mapM (resolveExternalUnit (optCompiler opts)) externalNames

expandExternalClosure :: [String] -> [String]
expandExternalClosure names =
  let expanded = sort . nub $ names ++ concatMap hackageDependencies names
   in if expanded == sort (nub names)
        then expanded
        else expandExternalClosure expanded

componentDependencyNames :: PackageDescription -> [String]
componentDependencyNames desc =
  map dependencyPackageName $
    concat
      [ maybe [] (targetBuildDepends . libBuildInfo) (library desc)
      , concatMap (targetBuildDepends . libBuildInfo) (subLibraries desc)
      , concatMap (targetBuildDepends . buildInfo) (executables desc)
      , concatMap (targetBuildDepends . testBuildInfo) (testSuites desc)
      , concatMap (targetBuildDepends . benchmarkBuildInfo) (benchmarks desc)
      ]

dependencyPackageName :: Dependency -> String
dependencyPackageName =
  takeWhile (not . isSpace) . prettyShow

resolveExternalUnit :: String -> String -> IO ExternalUnit
resolveExternalUnit compiler name =
  case lookup name (bootRegistry compiler) of
    Just version ->
      pure ExternalUnit {externalUnitName = name, externalUnitVersion = version, externalUnitSource = GhcBoot}
    Nothing ->
      case lookup name hackageRegistry of
        Just (version, url, sha256) ->
          pure
            ExternalUnit
              { externalUnitName = name
              , externalUnitVersion = version
              , externalUnitSource =
                  HackageSdist
                    { hackageSdistUrl = url
                    , hackageSdistSha256 = sha256
                    }
              }
        Nothing ->
          die $
            "penance-lock: no pinned source metadata for external dependency `"
              ++ name
              ++ "` with compiler "
              ++ compiler

bootRegistry :: String -> [(String, String)]
bootRegistry compiler =
  let baseVersion =
        case compiler of
          "ghc-9.10.2" -> "4.20.1.0"
          "ghc-9.10.3" -> "4.20.2.0"
          _ -> "4.20.2.0"
      bytestringVersion =
        case compiler of
          "ghc-9.10.2" -> "0.12.1.0"
          "ghc-9.10.3" -> "0.12.2.0"
          _ -> "0.12.2.0"
   in sort
        [ ("base", baseVersion)
        , ("bytestring", bytestringVersion)
        , ("containers", "0.7")
        , ("stm", "2.5.3.1")
        , ("template-haskell", "2.22.0.0")
        , ("transformers", "0.6.1.1")
        ]

hackageRegistry :: [(String, (String, String, String))]
hackageRegistry =
  sort
    [ ( "StateVar"
      ,
        ( "1.2.2"
        , "https://hackage.haskell.org/package/StateVar-1.2.2/StateVar-1.2.2.tar.gz"
        , "sha256-Xks52jlWVqWYJ7AoBQiq/ccDNXmLUOXW/VJZYCYlGCU="
        )
      )
    ]

hackageDependencies :: String -> [String]
hackageDependencies name =
  case name of
    "StateVar" -> ["base", "stm", "transformers"]
    _ -> []

externalUnitJson :: ExternalUnit -> Json
externalUnitJson unit =
  Json.object $
    [ ("name", Json.string (externalUnitName unit))
    , ("version", Json.string (externalUnitVersion unit))
    ]
      ++ case externalUnitSource unit of
        GhcBoot ->
          [("source", Json.string "ghc-boot")]
        HackageSdist url sha256 ->
          [ ("source", Json.string "hackage")
          , ( "sdist"
            , Json.object
                [ ("url", Json.string url)
                , ("sha256", Json.string sha256)
                ]
            )
          ]

sortOnPackage :: [PackageLock] -> [PackageLock]
sortOnPackage =
  sortOn (\packageLock -> prettyShow (pkgName (package (lockDescription packageLock))))

stringArray :: [String] -> Json
stringArray = Json.array . map Json.string

stripComment :: String -> String
stripComment = stripDoubleDash

stripDoubleDash :: String -> String
stripDoubleDash input =
  case input of
    '-' : '-' : _ -> ""
    ch : rest -> ch : stripDoubleDash rest
    "" -> ""

isIndented :: String -> Bool
isIndented (ch : _) = ch == ' ' || ch == '\t'
isIndented "" = False

trim :: String -> String
trim = dropWhileEnd isSpace . dropWhile isSpace

removeSuffix :: Eq a => [a] -> [a] -> [a]
removeSuffix suffix value =
  fromMaybe value (stripSuffix suffix value)

stripSuffix :: Eq a => [a] -> [a] -> Maybe [a]
stripSuffix suffix value =
  fmap reverse (stripPrefix (reverse suffix) (reverse value))
