module Main (main) where

import Control.Monad (forM, unless, when)
import qualified Data.ByteString as BS
import Data.Char (isSpace)
import Data.List (nub, sort, sortBy, stripPrefix)
import Data.Maybe (fromMaybe)
import Data.Ord (comparing)
import Distribution.Fields.ParseResult (runParseResult)
import Distribution.PackageDescription
  ( Benchmark (..)
  , BuildInfo (..)
  , Executable (..)
  , Library (..)
  , PackageDescription (..)
  , TestSuite (..)
  , buildType
  , pkgName
  , pkgVersion
  )
import Distribution.PackageDescription.Configuration (flattenPackageDescription)
import Distribution.PackageDescription.Parsec (parseGenericPackageDescription)
import Distribution.Pretty (prettyShow)
import Distribution.Types.LibraryName (LibraryName (..))
import Penance.Json (Json)
import qualified Penance.Json as Json
import System.Directory (listDirectory)
import System.Environment (getArgs)
import System.Exit (die, exitFailure, exitSuccess)
import System.FilePath ((</>), takeExtension)

data Options = Options
  { optProject :: FilePath
  , optCompiler :: String
  , optIndexState :: String
  , optOut :: Maybe FilePath
  , optCheck :: Maybe FilePath
  }
  deriving (Eq, Show)

data PackageLock = PackageLock
  { lockPackagePath :: FilePath
  , lockCabalFile :: FilePath
  , lockDescription :: PackageDescription
  }

main :: IO ()
main = do
  opts <- parseOptions =<< getArgs
  packages <- readProjectPackages opts
  let rendered = Json.renderJson (lockJson opts packages) ++ "\n"
  case optCheck opts of
    Just path -> do
      expected <- readFile path
      unless (expected == rendered) $ do
        putStrLn ("penance-lock: lock is stale: " ++ path)
        putStrLn "expected checked-in lock to match generated lock"
        exitFailure
    Nothing ->
      pure ()
  case optOut opts of
    Just path -> writeFile path rendered
    Nothing ->
      when (optCheck opts == Nothing) (putStr rendered)
  exitSuccess

parseOptions :: [String] -> IO Options
parseOptions =
  go
    Options
      { optProject = "."
      , optCompiler = "ghc-9.10.2"
      , optIndexState = "unknown"
      , optOut = Nothing
      , optCheck = Nothing
      }
  where
    go opts args =
      case args of
        [] -> pure opts
        "--project" : value : rest -> go opts {optProject = value} rest
        "--compiler" : value : rest -> go opts {optCompiler = value} rest
        "--index-state" : value : rest -> go opts {optIndexState = value} rest
        "--out" : value : rest -> go opts {optOut = Just value} rest
        "--check" : value : rest -> go opts {optCheck = Just value} rest
        "-h" : _ -> usage >> exitSuccess
        "--help" : _ -> usage >> exitSuccess
        flag : _ -> die ("unknown option: " ++ flag)

usage :: IO ()
usage =
  putStrLn $
    unlines
      [ "usage: penance-lock [--project DIR] [--compiler GHC] [--index-state TS] [--out FILE] [--check FILE]"
      , ""
      , "Generate a deterministic local-unit lock from cabal.project using Cabal as a library."
      , "--check compares the generated bytes with an existing lock file."
      ]

readProjectPackages :: Options -> IO [PackageLock]
readProjectPackages opts = do
  projectText <- readFile (optProject opts </> "cabal.project")
  let packagePaths = simpleProjectPackages projectText
  locks <- forM packagePaths $ \packagePath -> do
    cabalFile <- findCabalFile (optProject opts) packagePath
    cabalBytes <- BS.readFile cabalFile
    generic <-
      case runParseResult (parseGenericPackageDescription cabalBytes) of
        (_warnings, Right value) -> pure value
        (_warnings, Left err) -> die ("penance-lock: failed to parse " ++ cabalFile ++ ": " ++ show err)
    pure
      PackageLock
        { lockPackagePath = packagePath
        , lockCabalFile = makeRelativeProject packagePath cabalFile
        , lockDescription = flattenPackageDescription generic
        }
  pure (sortOnPackage locks)

findCabalFile :: FilePath -> FilePath -> IO FilePath
findCabalFile projectRoot packagePath = do
  let dir = if packagePath == "." then projectRoot else projectRoot </> packagePath
  entries <- listDirectory dir
  let cabalFiles = sort [entry | entry <- entries, takeExtension entry == ".cabal"]
  case cabalFiles of
    [name] -> pure (dir </> name)
    [] -> die ("penance-lock: no .cabal file found in " ++ dir)
    _ -> die ("penance-lock: multiple .cabal files found in " ++ dir)

makeRelativeProject :: FilePath -> FilePath -> FilePath
makeRelativeProject packagePath cabalFile =
  if packagePath == "."
    then lastPathPart cabalFile
    else packagePath </> lastPathPart cabalFile

lastPathPart :: FilePath -> FilePath
lastPathPart path =
  case reverse (splitOn '/' path) of
    name : _ -> name
    [] -> path

simpleProjectPackages :: String -> [FilePath]
simpleProjectPackages text =
  case collectProjectFieldPackages "packages" (projectLineRecords text) of
    [] -> ["."]
    paths -> sort (nub paths)

projectLineRecords :: String -> [(String, Bool)]
projectLineRecords text =
  [ (trim (stripComment line), isIndented (stripComment line))
  | line <- lines text
  , trim (stripComment line) /= ""
  ]

collectProjectFieldPackages :: String -> [(String, Bool)] -> [FilePath]
collectProjectFieldPackages field records =
  case records of
    [] -> []
    (line, indented) : rest
      | not indented && (field ++ ":") `isPrefixOf` line ->
          let inline = trim (drop (length field + 1) line)
              (continuation, remaining) = span snd rest
              value = unlines (inline : map fst continuation)
           in splitProjectPackageWords value ++ collectProjectFieldPackages field remaining
      | otherwise -> collectProjectFieldPackages field rest

splitProjectPackageWords :: String -> [FilePath]
splitProjectPackageWords value =
  filter (/= "") $
    map (trim . removeSuffix ",") $
      words (map (\ch -> if ch == '\t' || ch == '\n' then ' ' else ch) value)

lockJson :: Options -> [PackageLock] -> Json
lockJson opts packages =
  Json.object
    [ ("schema", Json.string "penance/strata-lock/0")
    , ("compiler", Json.string (optCompiler opts))
    , ("indexState", Json.string (optIndexState opts))
    , ( "project"
      , Json.object
          [ ("root", Json.string ".")
          , ("pathBase", Json.string "project-root")
          , ("cabalProject", Json.string "cabal.project")
          , ("packages", Json.array (map (Json.string . lockPackagePath) packages))
          ]
      )
    , ("packages", Json.array (map packageJson packages))
    ]

packageJson :: PackageLock -> Json
packageJson packageLock =
  let desc = lockDescription packageLock
   in Json.object
        [ ("name", Json.string (prettyShow (pkgName (package desc))))
        , ("version", Json.string (prettyShow (pkgVersion (package desc))))
        , ("path", Json.string (lockPackagePath packageLock))
        , ("cabalFile", Json.string (lockCabalFile packageLock))
        , ("setupType", Json.string (prettyShow (buildType desc)))
        , ("components", Json.array (componentsJson desc))
        ]

componentsJson :: PackageDescription -> [Json]
componentsJson desc =
  sortJsonBy renderedName $
    maybe [] (\lib -> [libraryJson "lib" lib]) (library desc)
      ++ map subLibraryJson (subLibraries desc)
      ++ map executableJson (executables desc)
      ++ map testSuiteJson (testSuites desc)
      ++ map benchmarkJson (benchmarks desc)
  where
    renderedName value =
      case value of
        Json.JsonObject fields ->
          case lookup "name" fields of
            Just (Json.JsonString name) -> name
            _ -> ""
        _ -> ""

libraryJson :: String -> Library -> Json
libraryJson name lib =
  componentJson name "library" (libBuildInfo lib) (map prettyShow (exposedModules lib)) (map prettyShow (signatures lib))

subLibraryJson :: Library -> Json
subLibraryJson lib =
  libraryJson (libraryComponentName (libName lib)) lib

executableJson :: Executable -> Json
executableJson exe =
  componentJson ("exe:" ++ prettyShow (exeName exe)) "executable" (buildInfo exe) [modulePath exe] []

testSuiteJson :: TestSuite -> Json
testSuiteJson test =
  componentJson ("test:" ++ prettyShow (testName test)) "test-suite" (testBuildInfo test) [] []

benchmarkJson :: Benchmark -> Json
benchmarkJson bench =
  componentJson ("bench:" ++ prettyShow (benchmarkName bench)) "benchmark" (benchmarkBuildInfo bench) [] []

libraryComponentName :: LibraryName -> String
libraryComponentName libraryName =
  case libraryName of
    LMainLibName -> "lib"
    LSubLibName name -> "lib:" ++ prettyShow name

componentJson :: String -> String -> BuildInfo -> [String] -> [String] -> Json
componentJson name kind buildInfo' modules signatures' =
  Json.object
    [ ("name", Json.string name)
    , ("kind", Json.string kind)
    , ("sourceDirs", stringArray (sort (map prettyShow (hsSourceDirs buildInfo'))))
    , ("modules", stringArray (sort modules))
    , ("signatures", stringArray (sort signatures'))
    , ("dependencies", stringArray (sort (map prettyShow (targetBuildDepends buildInfo'))))
    , ("defaultExtensions", stringArray (sort (map prettyShow (defaultExtensions buildInfo'))))
    ]

sortOnPackage :: [PackageLock] -> [PackageLock]
sortOnPackage =
  sortByKey (\packageLock -> prettyShow (pkgName (package (lockDescription packageLock))))

sortJsonBy :: (a -> String) -> [a] -> [a]
sortJsonBy = sortByKey

sortByKey :: (a -> String) -> [a] -> [a]
sortByKey key =
  sortBy (comparing key)

stringArray :: [String] -> Json
stringArray = Json.array . map Json.string

stripComment :: String -> String
stripComment = stripDoubleDash

stripDoubleDash :: String -> String
stripDoubleDash input =
  case input of
    '-' : '-' : _ -> ""
    ch : rest -> ch : stripDoubleDash rest
    "" -> ""

isIndented :: String -> Bool
isIndented (ch : _) = ch == ' ' || ch == '\t'
isIndented "" = False

trim :: String -> String
trim = dropWhileEnd isSpace . dropWhile isSpace

dropWhileEnd :: (a -> Bool) -> [a] -> [a]
dropWhileEnd predicate = reverse . dropWhile predicate . reverse

removeSuffix :: Eq a => [a] -> [a] -> [a]
removeSuffix suffix value =
  fromMaybe value (stripSuffix suffix value)

stripSuffix :: Eq a => [a] -> [a] -> Maybe [a]
stripSuffix suffix value =
  fmap reverse (stripPrefix (reverse suffix) (reverse value))

isPrefixOf :: Eq a => [a] -> [a] -> Bool
isPrefixOf prefix value =
  take (length prefix) value == prefix

splitOn :: Eq a => a -> [a] -> [[a]]
splitOn separator =
  go []
  where
    go acc input =
      case input of
        [] -> [reverse acc]
        x : xs
          | x == separator -> reverse acc : go [] xs
          | otherwise -> go (x : acc) xs
