# Generated by repent 0.1.0.0. DO NOT EDIT.
# Regenerate together with penance.lock so Cabal metadata and sdist hashes stay reviewable.
{
  mkDerivation,
  base,
  lib,
  stm,
  transformers,
}:
mkDerivation {
  pname = "StateVar";
  version = "1.2.2";
  sha256 = "5e4b39da395656a59827b0280508aafdc70335798b50e5d6fd52596026251825";
  libraryHaskellDepends = [
    base
    stm
    transformers
  ];
  homepage = "https://github.com/haskell-opengl/StateVar";
  description = "State variables";
  license = lib.licenses.bsd3;
}
